#!/usr/bin/env bash
#
# vdd-blast.sh — compute blast radius when a broadcast key changes
#
# Usage:
#   vdd blast <key>
#
# Examples:
#   vdd blast native:expired
#   vdd blast "auth/_state-contract#native:expired"
#   vdd blast phase:verified
#
# Output:
#   - direct reactors (pages declaring reacts_to)
#   - indirect emitters (pages declaring emits_to — side-effect triggers)
#   - layer impact summary (which layers are affected)
#   - additional cross-layer dependency hints

set -uo pipefail

# Plugin-only SoT — invoked via the `vdd` dispatcher (plugin bin/ on PATH).
LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${CODEX_PROJECT_DIR:-${CLAUDE_PROJECT_DIR:-$PWD}}"
VAULT="$PROJECT_ROOT/docs/vault"
if [ ! -d "$VAULT" ]; then
  echo "ERROR: no docs/vault/ at $PROJECT_ROOT — run from a project root or set CODEX_PROJECT_DIR or CLAUDE_PROJECT_DIR" >&2
  exit 1
fi

# Canonical YAML extractors — sourced from plugin path.
_VDD_LIB="$LIB_DIR/vdd-yaml-lib.sh"
if ! . "$_VDD_LIB" 2>/dev/null; then
  echo "ERROR: $_VDD_LIB not found — plugin install may be corrupt (re-run claude plugin install vault-driven-development@pdev-jay)" >&2
  exit 1
fi

if [ $# -lt 1 ]; then
  cat <<EOF >&2
Usage: vdd-blast <key>

  <key>:
    - bare:    "native:expired"  or  "phase:verified"
    - anchor:  "auth/_state-contract#native:expired"

Examples:
  vdd blast native:expired
  vdd blast "auth/_state-contract#native:expired"
EOF
  exit 1
fi

INPUT_KEY="$1"

# Normalize: strip path# prefix → key part only
NORM_KEY="$INPUT_KEY"
if [[ "$INPUT_KEY" == *"#"* ]]; then
  NORM_KEY="${INPUT_KEY#*#}"
fi

cd "$VAULT" || exit 1

# Verify _reverse-index.md exists (generated by lint)
if [ ! -f "_reverse-index.md" ]; then
  echo "ERROR: _reverse-index.md not found. Run: vdd lint" >&2
  exit 1
fi

# extract_list is provided by the sourced scripts/vdd-yaml-lib.sh (canonical).

# Helper: normalize key (strip path#)
norm() {
  local k="$1"
  if [[ "$k" == *"#"* ]]; then echo "${k#*#}"; else echo "$k"; fi
}

# Find pages that broadcast this key (emitters direct)
EMITTERS=()
while IFS= read -r f; do
  while IFS= read -r b; do
    [[ -z "$b" ]] && continue
    if [[ "$(norm "$b")" == "$NORM_KEY" ]]; then
      slug="$(basename "${f#./}" .md)"
      EMITTERS+=("$slug:${f#./}")
      break
    fi
  done < <(extract_list "$f" "broadcasts")
done < <(find . -type f -name "*.md" ! -name "_reverse-index.md" ! -name "_progress.md" ! -name "_decisions.md" ! -name "_open-issues.md" ! -path "./examples/*" ! -path "./_archive/*" ! -path "*.removed.*" ! -path "*.bak.*" | sort)

# Find reactors (reacts_to)
REACTORS=()
while IFS= read -r f; do
  while IFS= read -r r; do
    [[ -z "$r" ]] && continue
    if [[ "$(norm "$r")" == "$NORM_KEY" ]]; then
      slug="$(basename "${f#./}" .md)"
      REACTORS+=("$slug:${f#./}")
      break
    fi
  done < <(extract_list "$f" "reacts_to")
done < <(find . -type f -name "*.md" ! -name "_reverse-index.md" ! -name "_progress.md" ! -name "_decisions.md" ! -name "_open-issues.md" ! -path "./examples/*" ! -path "./_archive/*" ! -path "*.removed.*" ! -path "*.bak.*" | sort)

# Find indirect emitters (emits_to)
INDIRECT=()
while IFS= read -r f; do
  while IFS= read -r e; do
    [[ -z "$e" ]] && continue
    if [[ "$(norm "$e")" == "$NORM_KEY" ]]; then
      slug="$(basename "${f#./}" .md)"
      INDIRECT+=("$slug:${f#./}")
      break
    fi
  done < <(extract_list "$f" "emits_to")
done < <(find . -type f -name "*.md" ! -name "_reverse-index.md" ! -name "_progress.md" ! -name "_decisions.md" ! -name "_open-issues.md" ! -path "./examples/*" ! -path "./_archive/*" ! -path "*.removed.*" ! -path "*.bak.*" | sort)

# Layer extraction (first segment of path)
extract_layer() {
  local p="$1"
  echo "${p%%/*}"
}

# Print report
echo "═══════════════════════════════════════════════"
echo "vdd blast: \`$INPUT_KEY\`"
echo "  normalized key: \`$NORM_KEY\`"
echo "═══════════════════════════════════════════════"
echo

# Direct emitters (e.g. state-contract)
if [ ${#EMITTERS[@]} -gt 0 ]; then
  echo "▼ Direct emitters (broadcasts: $NORM_KEY)"
  for e in "${EMITTERS[@]}"; do
    slug="${e%%:*}"
    path="${e#*:}"
    echo "  - [[$slug]]  ($path)"
  done
  echo
fi

# Direct reactors
if [ ${#REACTORS[@]} -gt 0 ]; then
  echo "▼ Direct reactors (reacts_to)"
  for r in "${REACTORS[@]}"; do
    slug="${r%%:*}"
    path="${r#*:}"
    echo "  - [[$slug]]  ($path)"
  done
  echo
else
  echo "▼ Direct reactors: (none)"
  echo
fi

# Indirect emitters (side-effect triggers)
if [ ${#INDIRECT[@]} -gt 0 ]; then
  echo "▼ Indirect emitters (emits_to — side-effect triggers)"
  for i in "${INDIRECT[@]}"; do
    slug="${i%%:*}"
    path="${i#*:}"
    echo "  - [[$slug]]  ($path)"
  done
  echo
else
  echo "▼ Indirect emitters: (none)"
  echo
fi

# Layer impact summary
LAYERS=$(
  {
    if [ ${#EMITTERS[@]} -gt 0 ]; then
      for e in "${EMITTERS[@]}";  do extract_layer "${e#*:}"; done
    fi
    if [ ${#REACTORS[@]} -gt 0 ]; then
      for r in "${REACTORS[@]}";  do extract_layer "${r#*:}"; done
    fi
    if [ ${#INDIRECT[@]} -gt 0 ]; then
      for i in "${INDIRECT[@]}";  do extract_layer "${i#*:}"; done
    fi
  } | sort -u | grep -v '^$'
)
LAYER_COUNT=$(echo "$LAYERS" | grep -c . | tr -d ' \n')
[ -z "$LAYER_COUNT" ] && LAYER_COUNT=0

echo "▼ Layer impact summary"
echo "  affected layers: $LAYER_COUNT"
if [ "$LAYER_COUNT" -gt 0 ]; then
  echo "$LAYERS" | sed 's/^/    - /'
fi
echo

# Total page count
TOTAL=$(( ${#EMITTERS[@]} + ${#REACTORS[@]} + ${#INDIRECT[@]} ))
echo "▼ Total affected pages: $TOTAL"
echo

if [ "$TOTAL" -eq 0 ]; then
  echo "WARNING: no reactor/emitter for key \`$NORM_KEY\`."
  echo "  - Is the key correct? Check declared keys with \`grep -rn 'broadcasts:' --include=\"*.md\"\`"
  echo "  - Is lint up to date? \`vdd lint\`"
  exit 1
fi

echo "═══════════════════════════════════════════════"
echo "Next action candidates:"
echo "  - review each reactor page (change impact)"
echo "  - update state-contract page (emitter) first"
echo "  - invoke vault-verifier to check affected pages for consistency"
echo "═══════════════════════════════════════════════"
